<?php

namespace ContainerHZQpMHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUofxK6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yUofxK6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yUofxK6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'posts' => ['privates', '.errored..service_locator.yUofxK6.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.yUofxK6": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'posts' => 'App\\Entity\\Post',
        ]);
    }
}
