<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBKICGJA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBKICGJA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBKICGJA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBKICGJA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBKICGJA\App_KernelDevDebugContainer([
    'container.build_hash' => 'BKICGJA',
    'container.build_id' => '5cf24b67',
    'container.build_time' => 1607935100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBKICGJA');
