<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVc2c5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVc2c5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJVc2c5W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJVc2c5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJVc2c5W\App_KernelDevDebugContainer([
    'container.build_hash' => 'JVc2c5W',
    'container.build_id' => '73ab98eb',
    'container.build_time' => 1607943318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVc2c5W');
