<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF5mudxa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF5mudxa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF5mudxa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF5mudxa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF5mudxa\App_KernelDevDebugContainer([
    'container.build_hash' => 'F5mudxa',
    'container.build_id' => 'cbe1dde2',
    'container.build_time' => 1605526687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF5mudxa');
